# SPDX-FileCopyrightText: 2021 The HedgeDoc developers (see AUTHORS file)
#
# SPDX-License-Identifier: AGPL-3.0-only

name: Setup Node
description: "Setups node and configures the cache"

inputs:
  NODEJS_VERSION:
    required: true
    description: "NodeJS version to install"

runs:
  using: "composite"
  steps:
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache yarn cache
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-node${{ inputs.NODEJS_VERSION }}-yarn-master

    - name: Set up NodeJS
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: ${{ inputs.NODEJS_VERSION }}

    - name: Install dependencies
      run: yarn install --immutable
      working-directory: .
      shell: bash
