language: node_js
dist: trusty
cache: yarn
env:
  global:
    - CXX=g++-4.8
    - YARN_VERSION=1.16.0

jobs:
  include:
    - env: task=npm-test
      node_js:
        - 8
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version "$YARN_VERSION"
        - export PATH="$HOME/.yarn/bin:$PATH"
    - env: task=npm-test
      node_js:
        - 10
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version "$YARN_VERSION"
        - export PATH="$HOME/.yarn/bin:$PATH"
    - env: task=npm-test
      node_js:
        - 12
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version "$YARN_VERSION"
        - export PATH="$HOME/.yarn/bin:$PATH"
    - env: task=ShellCheck
      script:
        - shellcheck bin/heroku bin/setup
      language: generic
    - env: task=json-lint
      addons:
        apt:
          packages:
          - jq
      script:
        - npm run jsonlint
      language: generic
