language: node_js
dist: xenial
cache: yarn

jobs:
  include:
    - stage: Static Tests
      name: eslint
      node_js:
        - 10
      script:
        - yarn run eslint
    - name: ShellCheck
      script:
        - shellcheck bin/heroku bin/setup
      language: generic
    - name: json-lint
      addons:
        apt:
          packages:
          - jq
      script:
        - yarn run jsonlint
      language: generic
    - stage: Dynamic Tests
      name: Node.js 8
      node_js:
        - 8
      script:
        - yarn run mocha-suite
    - name: Node.js 10
      node_js:
        - 10
      script:
        - yarn run mocha-suite
    - name: Node.js 12
      node_js:
        - 12
      script:
        - yarn run mocha-suite
