# SPDX-FileCopyrightText: 2025 The HedgeDoc developers (see AUTHORS file)
# SPDX-License-Identifier: AGPL-3.0-only
---
services:
  mariadb:
    # renovate: datasource=docker depName=mariadb
    image: mariadb:12.3.3@sha256:dd9b303aed4f4890ed09f766d8ca9ddfd176c0c6f6267feff53b3192ec65a979
    environment:
      MARIADB_USER: hedgedoc
      MARIADB_PASSWORD: hedgedoc
      MARIADB_DATABASE: hedgedoc
      MARIADB_ROOT_PASSWORD: hedgedoc
      MARIADB_MYSQL_LOCALHOST_USER: 1
      MARIADB_MYSQL_LOCALHOST_GRANTS: USAGE
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3306:3306"
  postgres:
    # renovate: datasource=docker depName=postgres
    image: postgres:18.6@sha256:4ef4dbc939d61acea57712655ddb4b4ab27419c913f94cca0cd57cb3ea3c2280
    environment:
      POSTGRES_PASSWORD: hedgedoc
      POSTGRES_USER: hedgedoc
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      start_period: 10s
      interval: 5s
      timeout: 2s
      retries: 5
    ports:
      - "5432:5432"
