name: Bug report
description: Create a report to help us improve HedgeDoc.
title: "type a short title of your bug report here"
labels: ["type: bug"]
body:
  - type: markdown
    attributes:
      value: |
        - If you're requesting an improvement for an existing feature, then please consider filling out an "enhancement request" instead!
        - If you're requesting a new feature, that isn't part of this project yet, then please consider filling out a "feature request" instead!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: What did you do to reproduce the behavior?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: If applicable, add an excerpt from the server logs where the error is reported. Remember to censor sensitive values.
      render: shell
    validations:
      required: false
  - type: textarea
    id: config
    attributes:
      label: Config
      description: If applicable, copy and paste your config (or ideally only relevant parts of it) here. Remember to censor sensitive values.
      render: shell
    validations:
      required: false
  - type: textarea
    id: setup
    attributes:
      label: Your Setup
      description: Please complete the following information.
      value: |
        - Host OS: [e.g. Ubuntu 20.04]
        - NodeJS version: [run `node --version`]
        - HedgeDoc version: (Click "Releases" in the footer)
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
