# SPDX-FileCopyrightText: 2021 The HedgeDoc developers (see AUTHORS file)
#
# SPDX-License-Identifier: AGPL-3.0-only


name: Backend / Lint and Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.job }}
  cancel-in-progress: true

env:
  NODEJS_VERSION: 18

defaults:
  run:
    working-directory: backend

jobs:
  changes:
    name: Check for backend changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      changed: ${{ github.event_name == 'push' || steps.changed.outputs.files }}
    steps:
      - uses: actions/checkout@v3
        if: github.event_name != 'push'

      - name: Check for backend file changes
        if: github.event_name != 'push'
        uses: dorny/paths-filter@v2
        id: changed
        with:
          filters: |
            files:
              - 'commons/**'
              - 'backend/**'
              - '.github/**'
              - '.yarn/**'

  lint:
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: needs.changes.outputs.changed == 'true'

      - name: Setup node
        if: needs.changes.outputs.changed == 'true'
        uses: ./.github/actions/setup-node
        with:
          NODE_VERSION: ${{ env.NODEJS_VERSION }}

      - run: yarn run lint
        if: needs.changes.outputs.changed == 'true'

  build:
    needs: changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 18.x ]
    steps:
      - uses: actions/checkout@v3
        if: needs.changes.outputs.changed == 'true'

      - name: Setup node
        if: needs.changes.outputs.changed == 'true'
        uses: ./.github/actions/setup-node
        with:
          NODE_VERSION: ${{ env.NODE_VERSION }}

      - run: yarn run build
        if: needs.changes.outputs.changed == 'true'

  integration-tests:
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: needs.changes.outputs.changed == 'true'
        with:
          fetch-depth: 0

      - name: Setup node
        if: needs.changes.outputs.changed == 'true'
        uses: ./.github/actions/setup-node
        with:
          NODE_VERSION: ${{ env.NODE_VERSION }}

      - run: yarn run test:cov
        if: needs.changes.outputs.changed == 'true'

      - uses: codecov/codecov-action@v3
        if: needs.changes.outputs.changed == 'true'
        with:
          directory: backend/coverage
          flags: integration-tests
