# SPDX-FileCopyrightText: 2021 The HedgeDoc developers (see AUTHORS file)
#
# SPDX-License-Identifier: AGPL-3.0-only

name: REUSE Compliance Check

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  reuse:
    runs-on: ubuntu-latest
    container:
      image: fsfe/reuse:6.2.0@sha256:85462a75c0f8efda09ddd190b92816b70e7662577c8427429e11e1b9f25a992e
    steps:
      - uses: actions/checkout@v7.0.1

      - name: Run linter
        run: reuse lint
